# knitr::stitch_rmd(script="./manipulation/0-ellis-map.R", output="./manipulation/stitched-output/0-ellis-map.md")
# This script reads two files: encounter counts with location mapping and encounter timelines for selected individuals
rm(list=ls(all=TRUE)) #Clear the memory of variables from previous run. This is not called by knitr, because it's above the first chunk.

# ---- load-sources ------------------------------------------------------------
#Load any source files that contain/define functions, but that don't load any other types of variables
#   into memory.  Avoid side effects and don't pollute the global environment.
source("./manipulation/function-support.R")  # assisting functions for data wrangling and testing
source("./manipulation/object-glossary.R")   # object definitions
source("./scripts/common-functions.R")       # reporting functions and quick views
source("./scripts/graphing/graph-presets.R") # font and color conventions
# ---- load-packages -----------------------------------------------------------
library(ggplot2) #For graphing
library(dplyr)
library(magrittr) #Pipes

requireNamespace("knitr")
requireNamespace("scales") #For formating values in graphs
requireNamespace("RColorBrewer")
requireNamespace("dplyr")
requireNamespace("DT") # for dynamic tables

# ---- declare-globals ---------------------------------------------------------
# link to the source of the location mapping
# path_input_components <- "./data-public/raw/bc_health_system_components.csv"
# path_input_map <- "./data-public/raw/bc_health_system_map.csv"

path_input <- "./data-public/raw/fictional_cases/flower-deafness-all-years.csv"
# test whether the file exists / the link is good
# testit::assert("File does not exist", base::file.exists(path_input_components))
# testit::assert("File does not exist", base::file.exists(path_input_map))
testit::assert("File does not exist", base::file.exists(path_input))
# declare where you will store the product of this script
path_save <- "./data-unshared/derived/0-dto-made"
# See definitions of commonly  used objects in:
source("./manipulation/object-glossary.R")   # object definitions

# ---- utility-functions ----------------------------------------------------- 
# functions, the use of which is localized to this script

# ---- load-data ---------------------------------------------------------------
# ds_components <- readr::read_csv(path_input_components) %>% as.data.frame() 
# ds_map <- readr::read_csv(path_input_map) %>% as.data.frame() 
# let us read in a fictional case for FLOWER DEAFNESS generated by the proto_case_generator.xlsx
ds <- readr::read_csv(path_input) %>% as.data.frame()


# ---- inspect-data -----------------------------------------------------------
ds %>% dplyr::glimpse()

# ---- tweak-data -------------------------------------------------------------